### ISSUE TITLE
NPM page has incorrect import

### ISSUE THREAD

**Issue by moshejs** [lifeiscontent/storybook-addon-next-router#1]
In [NPM page ](https://www.npmjs.com/package/storybook-addon-next-router) we see:
`import { withNextRouter } from 'storybook-addon-apollo-client';`

which should be:

`import { withNextRouter } from 'storybook-addon-next-router';`

**Comment by lifeiscontent** [comment]
@moshejs never check NPM as a source of truth it only shows the readme of the latest deployed version. I have nothing new to deploy, so that's the reason for the inconsistency.

Once I have something worth deploying, it'll be updated.
