### ISSUE TITLE
Align documentation with Storybook Docs

### ISSUE THREAD

**Issue by ghost** [lifeiscontent/storybook-addon-next-router#12]
Storybook [docs give](https://storybook.js.org/docs/react/writing-stories/decorators) this pattern for adding decorators in `preview.js`:

```jsx
// .storybook/preview.js

import React from 'react';

export const decorators = [
  (Story) => (
    <div style={{ margin: '3em' }}>
      <Story />
    </div>
  ),
];
```

The `README` of this repo provides a different pattern:

```js
addDecorator(
  withNextRouter({
    path: '/', // defaults to `/`
    asPath: '/', // defaults to `/`
    query: {}, // defaults to `{}`
    push() {} // defaults to using addon actions integration, can override any method in the router
  })
);
```

To make this addon more useful, please update documentation to either (a) provide both methods in the storybook docs and/or (b) update the `README` of this repo to show how the addon can be incorporated into the pattern given in the Storybook documentation. Without the docs, this addon causes churn trying to figure it out.

**Comment by ghost** [comment]
It appears you may be missing documentation suggesting individuals add the addon to `main.js`. Saw that by looking at another addon readme: https://storybook.js.org/addons/storybook-addon-apollo-client

EDIT: I see this addon does not require itself to be added to the `addons` array in the Storybook config. That's worth calling out explicitly in the documentation.

**Comment by balibebas** [comment]
Here's how I achieve addition:

```
export const decorators = [
  (Story) => (
    <div style={{ margin: '3em' }}>
      <Story />
    </div>
  ),
  withNextRouter
]

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  nextRouter: {
    path: "/",
    asPath: "/",
    query: {},
    push() {},
  }
}
```

This is what's missing in the docs.

**Comment by ghost** [comment]
Here's how I achieve addition:

```jsx
export const decorators = [
  (Story) => (
    <div style={{ margin: '3em' }}>
      <Story />
    </div>
  ),
  withNextRouter
]

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  nextRouter: {
    path: "/",
    asPath: "/",
    query: {},
    push() {},
  }
}
```

This is what's missing in the docs.

**Comment by lifeiscontent** [comment]
@balibebas let me know if the changes I've made look reasonable to you.

**Comment by ghost** [comment]
Thank you for your responsiveness @lifeiscontent. I have not tested your changes but if it fits the bill and the build passes it's nice to see that we have even more options than what I had considered. :+1: the code snippet that I showed is based on the scaffolding that storybook provided with my project so I'm happy I was able to find a way not to have to refactor that to incorporate my first add-on which was this.
