### ISSUE TITLE
Add support for locales

### ISSUE THREAD

**Issue by quantizor** [lifeiscontent/storybook-addon-next-router#20]
Internationalized routing in next.js adds a [bunch of new properties to the `router` object](https://nextjs.org/docs/api-reference/next/router#router-object), it would be great if this library gave a way to initialize them for storybook use.

**Comment by lifeiscontent** [comment]
@probablyup it already does, you can literally use any properties from the next.js Router, its completely transparent.

**Comment by quantizor** [comment]
@lifeiscontent ah, maybe it would be helpful to add an example to the README to make that more clear
