### ISSUE TITLE
storybook fails to start because of tslib

### ISSUE THREAD

**Issue by xistz** [lifeiscontent/storybook-addon-next-router#29]
Thank you creating the addon. The addon fails to start if npm is used as the package manager. The issue seems to be with tslib and how npm/yarn manages package versions. The issue can be reproduced in this repository

https://github.com/xistz/next-storybook-addon-next-router

steps taken to create the respective directories

- npm

  ```shell
  npx create-next-app --ts
  npx sb init
  npm i -D storybook-addon-next-router
  ```

- yarn

  ```shell
  yarn create next-app --typescript
  npx sb init
  yarn add -D storybook-addon-next-router
  ```

error message from when starting storybook in the npm directory

<img width="1300" alt="Screenshot 2021-07-20 at 9 20 12" src="https://user-images.githubusercontent.com/25769723/126243661-6c3a0788-907b-4f45-a976-7082941c3c0b.png">

**Comment by dohomi** [comment]
I experience the same issue, is there a workaround?
I receive this error with yarn v2:
```
ERR! Error: storybook-addon-next-router tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```
And npm does fail with the error above.

**Comment by xistz** [comment]
I am not familiar with dependency resolution but I managed to work around it by running `npm i -D tslib@2.3.0`

**Comment by lifeiscontent** [comment]
@xistz I can remove tslib, but that would make the code larger, pretty sure other libraries that are written with TS can take advantage of tslib which will ultimately result in a smaller bundle size for you.

**Comment by xistz** [comment]
@lifeiscontent 
After a bit more investigation, I realised the issue could have also arose because my other packages were depending on an older version of tslib which didn't have `__spreadArray`.  Whenever those packages get updated, it will be probably be resolved. 

Until then, manually installing tslib is a workaround so I think it should be fine to leave it in.

Thanks for your help!
