### ISSUE TITLE
Wrong addon name in readme on npmjs

### ISSUE THREAD

**Issue by arbejd** [lifeiscontent/storybook-addon-next-router#30]
Readme looks correct on github where the addon is **"storybook-addon-next-router"**, but it says **"storybook-addon-apollo-client"** on npmjs

Screendump from npmjs:

![image](https://user-images.githubusercontent.com/72977466/126498963-313732f6-5329-4196-b485-8aa2fd4da66e.png)

**Comment by drichar** [comment]
Also incorrect on https://storybook.js.org/addons/storybook-addon-next-router

**Comment by cabbiepete** [comment]
FWIW results in this error on starting storybook

```
ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/
ERR! storybook-addon-apollo-client
```

**Comment by lifeiscontent** [comment]
@arbejd there's nothing I can do about this, npm only stores the README of the latest published npm package.
