### ISSUE TITLE
Storybook preview hooks can only be called inside decorators and story functions.

### ISSUE THREAD

**Issue by dohomi** [lifeiscontent/storybook-addon-next-router#31]
In NextJS 11.0.1 the initial Storybook does not render and throws an error:
```
Storybook preview hooks can only be called inside decorators and story functions.
Error: Storybook preview hooks can only be called inside decorators and story functions.
    at invalidHooksError (hooks.js:240)
    at useStoryContext (hooks.js:442)
    at Module.useGlobals (hooks.js:487)
    at WithNextRouter (decorators.js:11)
    at hooks.js:186
    at decorators.js:26
    at decorators.js:62
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
```
I use preview.tsx and my app initially does not render with the above error. But client side navigation works and renders accordingly.

**Comment by lifeiscontent** [comment]
@dohomi is this still an issue with the latest release?

**Comment by dohomi** [comment]
@lifeiscontent yes this issue was based on the latest version. I had to replace it with a different approach for now.

**Comment by vitorcamachoo** [comment]
> @lifeiscontent yes this issue was based on the latest version. I had to replace it with a different approach for now.

How did you manage to solve this error? Im getting this error too.

**Comment by lifeiscontent** [comment]
@vitorcamachoo @dohomi Can you create a reproduction? Would love to fix this issue, but I'm unable to reproduce

**Comment by dohomi** [comment]
@lifeiscontent I gave it another try in a different project, sorry I was backed up. Seems to be working now, maybe there was something down the line either in recent updates of Storybook or NextJS which fixed it unintentionally. Thanks for looping back in.

**Comment by dfalling** [comment]
I'm fully updated with NextJS, Storybook, and storybook-addon-next-router and experiencing the same issue. My project's pretty complex so I'll try to make a simpler project that reproduces the issue.

**Comment by dfalling** [comment]
Here's a simplified project that reproduces the issue:  https://github.com/dfalling/storybook-next-router-bug

**Comment by Myzel394** [comment]
Is there a solution available?

**Comment by lifeiscontent** [comment]
@Myzel394 the issue of the reproduction @dfalling had was due to having `@react-theming/storybook-addon` which is using the wrong hooks that storybook provides for addon creators. You might also be using an addon which also does this.
