### ISSUE TITLE
tslib should be a peer dependency

### ISSUE THREAD

**Issue by unixdev** [lifeiscontent/storybook-addon-next-router#33]
`tslib ^2.3.0` is listed as a dev dependency. My project does not have a direct dependency on `tslib`. One of my other dependencies used `tslib 1.x` as its dependency. Hence the `tslib` under my `node_modules` was of version 1.x. If I run:

`npm run storybook`

to run Storybook, I get this error:

```
info @storybook/react v6.3.7
info 
info => Loading presets
ERR! TypeError: tslib_1.__spreadArray is not a function
ERR!     at Object.config (/Users/masum/Projects/ieims-next/node_modules/storybook-addon-next-router/dist/preset.js:7:42)
ERR!     at /Users/masum/Projects/ieims-next/node_modules/@storybook/core-common/dist/cjs/presets.js:274:28
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This package needs `tslib 2.3.0+` to run. Any package using it must have this version of tslib or better. Hence it should be declared as a dependency or peer dependency.

As it is always used as a library and as `tslib` is often used by other packages, it probably makes better sense to declare the `tslib` dependency as a peer dependency.

**Comment by arjansingh** [comment]
I second this. I had to downgrade back to `2.0.4` because of this issue. I think it actually needs to be a full dependency and not just a peer dependency. I tried manually forcing `tslib@2.3.0` in my application and it still was defaulting to using an older version.

**Comment by lifeiscontent** [comment]
@arjansingh @unixdev my bad, I'll fix that now.

**Comment by lifeiscontent** [comment]
@unixdev can you try version 3.0.8 and see if that fixes your issues?

**Comment by arjansingh** [comment]
Yes. I will try it this upcoming week and report back.

**Comment by arjansingh** [comment]
Yup looks like we are good. Thanks!
