### ISSUE TITLE
Storybook preview hooks can only be called inside decorators and story functions w/ sample project

### ISSUE THREAD

**Issue by dfalling** [lifeiscontent/storybook-addon-next-router#34]
I'm still experiencing the issue documented in  #31 with fully updated dependencies:

```
Storybook preview hooks can only be called inside decorators and story functions.
Error: Storybook preview hooks can only be called inside decorators and story functions.
    at invalidHooksError (hooks.js:240)
    at useStoryContext (hooks.js:442)
    at Module.useGlobals (hooks.js:487)
    at WithNextRouter (decorators.js:11)
    at hooks.js:186
    at decorators.js:26
    at decorators.js:62
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
```

Here's a sample project that reproduces the issue: https://github.com/dfalling/storybook-next-router-bug

**Comment by lifeiscontent** [comment]
@dfalling this is not a bug in storybook-addon-next-router. its a bug here: https://github.com/react-theming/storybook-addon/blob/master/src/preview/index.js#L14-L18

they're using React.useEffect when they should be using the useEffect hook exposed by Storybook.

**Comment by dfalling** [comment]
Ah, got it, thank you!
