### ISSUE TITLE
Officially expose RouterContext in Next

### ISSUE THREAD

**Issue by eric-burel** [lifeiscontent/storybook-addon-next-router#35]
In order to make this lib more robust, Next should expose the RouterContext officially.

That would require a PR to Next directly, but I open it here because that's probably the best place to track it.

**Comment by lifeiscontent** [comment]
@eric-burel thanks for the help, let me know if I can do anything to assist. 👍🏻

**Comment by lifeiscontent** [comment]
@eric-burel safe to close this issue now?

**Comment by eric-burel** [comment]
Hi, not sure if it has been done/solved? My PR is still open in Next.js.

**Comment by rtrembecky** [comment]
Eric's idea was to keep this open to track a potential improvement of importing `RouterContext` from next via stable path (e.g. `from "next/client/router"`) and not from some arbitrary path like it is now (`from "next/dist/shared/lib/router-context"`). However, that would require Vercel team to merge https://github.com/vercel/next.js/pull/28528 and that may never come.

**Comment by rtrembecky** [comment]
As this issue is linked to that PR, I guess it is OK to keep this closed, it will be revisited with progress on https://github.com/vercel/next.js/pull/28528.
