### ISSUE TITLE
Not able to use the addon due to build error

### ISSUE THREAD

**Issue by kiliw** [lifeiscontent/storybook-addon-next-router#38]
I'm trying to install and use the addon since one of my components uses the next router and its query parameters. Unfortunately, I can't get the add-on to work. I followed the instructions but I get when starting storybook
```
ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/                                                                               
ERR! storybook-addon-next-router 
```
and
```
Can't resolve 'next/dist/next-server/lib/router-context'
```
Maybe this is because it's a monorepo?

I'd be very happy if there is a solution to use this addon. Cheers

**Comment by lifeiscontent** [comment]
@kiliw which version of next.js are you using?

**Comment by kiliw** [comment]
@lifeiscontent  oh sorry, I'm using 
`next: ^11.1.2`
`@storybook/react: ^6.3.8`

**Comment by lifeiscontent** [comment]
can you check to see if you're next package is indeed being installed correctly as a dependency to the project? also, I'd look to see if the import path is correct, I know the router-context has been moved around in recent versions of Next.js and it might of changed again.

**Comment by Wyctus** [comment]
@lifeiscontent 
Is there any update with this? Thank you!

**Comment by kiliw** [comment]
@lifeiscontent sorry, for the delay, had a week off. Maybe its because its a monorepo?

**Comment by lifeiscontent** [comment]
@kiliw can you try with the latest release?

**Comment by kiliw** [comment]
@lifeiscontent sorry for getting back so late. Now everything works fine, thank you very much :)
