### ISSUE TITLE
Storybook preview hooks can only be called inside decorators and story functions

### ISSUE THREAD

**Issue by ludorival** [lifeiscontent/storybook-addon-next-router#39]
Hi 👋 

First of all thank you for its addon 😃 .
 
I am using [`"@storybook/testing-react"`](https://storybook.js.org/addons/@storybook/testing-react) to reuse stories from my unit test. But when I mount the story component. I got this error when the next decorator is executed
```
Storybook preview hooks can only be called inside decorators and story functions
```

It comes from https://github.com/lifeiscontent/storybook-addon-next-router/blob/9d79a1aaef7964d8c2e31c6bcd29d8ed35190900/src/decorators.tsx#L12

There is a [related issue](https://github.com/storybookjs/testing-react/issues/30) into storybook but no concrete solution.

> Note that  `"@storybook/testing-react"`  is not able to apply the register function to add the decorator, we need to add it manually in the setGlobalConfig like 
```js
import * as sbPreview from "storybook/config/preview"
import { WithNextRouter } from "storybook-addon-next-router/dist/decorators";

sbPreview.decorators.push(WithNextRouter)

setGlobalConfig(sbPreview );
```

Could it be possible to provide directly the locale as a parameter when using the decorator ? Something like that ?
```js
export const WithNextRouter = (providedLocale?: string) =>  (
  Story: React.FC<unknown>,
  context: StoryContext
): JSX.Element => {
  const [{ locale }] = providedLocale ? [{locale: providedLocale}] : useGlobals();
...
```

Then I could use it in my test with a default locale 
```js
sbPreview.decorators.push(WithNextRouter('en'))

setGlobalConfig(sbPreview );
```

**Comment by rtrembecky** [comment]
hi, I'm just struggling with a similar problem. in my case, I'd like to use the provider inside my own decorator, because one of my other app providers tries to access `useRouter` (so I need the provider in the "global app setup", having it just for the tested components is not enough). I'm getting the same error when I try to use the `WithNextRouter` and supply other children in the place of `Story` argument.

BTW, note that `const [{ locale }] = providedLocale ? [{locale: providedLocale}] : useGlobals();` exactly wouldn't work - that's a conditionally called hook (forbidden by react).

I think the library was not meant to be used this way, so I think I'll just use Next's ReactContext directly and copy some of the library's code.

**Comment by ghost** [comment]
I encountered the same issue and struggled for a while, and came to the same conclusion: `const [{ locale }] = useGlobals(); ` cannot be used inside other addons renderings, so when adding the router addon it would only work for the story, but break for example, in my Docs addon.

My workaround was the same that @rtrembecky mentioned.
I copied some things from https://github.com/lifeiscontent/storybook-addon-next-router/blob/master/src/decorators.tsx and done my own provider in a decorator

```import { action } from '@storybook/addon-actions';
import { RouterContext } from 'next/dist/shared/lib/router-context';
import { ReactNode } from 'react';

const getRouter = () => {
    return {
        locale: 'en',
        route: '/',
        pathname: '/',
        query: {},
        asPath: '/',
        push(...args: unknown[]) {
            action('nextRouter.push')(...args);
            return Promise.resolve(true);
        },
        replace(...args: unknown[]) {
            action('nextRouter.replace')(...args);
            return Promise.resolve(true);
        },
        reload(...args: unknown[]) {
            action('nextRouter.reload')(...args);
        },
        back(...args: unknown[]) {
            action('nextRouter.back')(...args);
        },
        prefetch(...args: unknown[]) {
            action('nextRouter.prefetch')(...args);
            return Promise.resolve();
        },
        beforePopState(...args: unknown[]) {
            action('nextRouter.beforePopState')(...args);
        },
        events: {
            on(...args: unknown[]) {
                action('nextRouter.events.on')(...args);
            },
            off(...args: unknown[]) {
                action('nextRouter.events.off')(...args);
            },
            emit(...args: unknown[]) {
                action('nextRouter.events.emit')(...args);
            },
        },
        isFallback: false,
        basePath: '',
        isLocaleDomain: false,
        isReady: true,
        isPreview: false,
    };
};

export const StorybookRouterProvider = ({ children }: { children: ReactNode }) => (
    <RouterContext.Provider value={getRouter()}>{children}</RouterContext.Provider>
);
```

Then in my preview.js I've added

```
export const decorators = [
    (Story) => <StorybookRouterProvider children={<Story />} />,
]
```

**Comment by ludorival** [comment]
Thanks, indeed to unblock me I created my own decorator. I am closing it since we found a workaround.

**Comment by ghost** [comment]
@ludorival maybe consider leaving the issue open, it's a problem that would affect pretty much anyone using the extension. I know very little about writing SB extensions so I was hoping to hear from one of the contributors if this is a addon limitation or it's just something missing in the configuration to make it work on other plugins.
I thinking either the locale should have a default and come from parameters like asPath, pathname etc or the module can export both a WithNextRouter as a pure decorator and a WithLocalizedNextRouter and only the latter have a useGlobals?

**Comment by ludorival** [comment]
Alright @tccimpact

**Comment by lifeiscontent** [comment]
@tccimpact @ludorival if either of you could provide a minimal reproduction I'd be happy to fix this, but I haven't personally run into this issue so its a bit hard for me to track down.
