### ISSUE TITLE
support for next@10.x peer dependency ?

### ISSUE THREAD

**Issue by niicfyi** [lifeiscontent/storybook-addon-next-router#4]
Hello there, thank you for the add-on, it has been very helpful 👍 

Is a peer dependency bump from next@9.x to 10.x somewhere in the release pipeline?
https://github.com/lifeiscontent/storybook-addon-next-router/blob/fe06b5f79406e5f985cc1adc0258beb0837536bc/package.json#L43

I'm currently having dependency conflicts while using it on a project running next 10.x

**Comment by lifeiscontent** [comment]
@niiccolas want to submit a PR? something like:

```
"next": "9.x || 10.x", 
```
