### ISSUE TITLE
Pathname not being updated

### ISSUE THREAD

**Issue by lapa182** [lifeiscontent/storybook-addon-next-router#46]
After we updated Storybook to 6.4 and the package to the latest version, the story nextRouter parameter stopped updating `pathname`.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/2954009/144077431-9e56adbf-9673-4653-bd61-dfadd47ce49a.png">

And my component story configuration:

```
WithActiveClass.story = {
  parameters: {
    nextRouter: {
      path: '/[org]/tutorial/[offerRequestId]',
      query: {
        offerRequestId: 'orq_0000ACaWmBMrOUgkQAC360',
        offerId: 'off_0000ACaXwkSnuiy2O5ByAk',
      },
      asPath: '/duffel/tutorial/orq_0000ACaWmBMrOUgkQAC360',
    },
  },
}
```

Even if I update `path` to `pathname` (as it was before) it doesn't work.

**Comment by lapa182** [comment]
I've raised a PR fixing it: https://github.com/lifeiscontent/storybook-addon-next-router/pull/47

**Comment by brvnonascimento** [comment]
Experiencing the same issue for the "query" property, the "path" property updated just fine.

**Comment by lifeiscontent** [comment]
Fixed in latest release, sorry about that everyone!
