### ISSUE TITLE
All values except `path` are being overwritten by defaults

### ISSUE THREAD

**Issue by LionC** [lifeiscontent/storybook-addon-next-router#48]
When using the addon according to the documentation, my actual story only "sees" the `path` property I have set - all the other properties are set to defaults.

Looking into the code, I think I found why that is the case - the spread of the provided parameters has recently been moved to the top, which overwrites all given properties expect `path` (because `path` has no default). It seems this change was introduced in #45 :

https://github.com/lifeiscontent/storybook-addon-next-router/blob/7e844ec5e37f4e62a0a951f587a05a60e982202c/src/decorators.tsx#L17

**Comment by lifeiscontent** [comment]
@LionC sorry! I'll push out a release shortly!
