### ISSUE TITLE
Reading properties of undefined error with WithNextRouter and Storybook

### ISSUE THREAD

**Issue by NixoN2** [lifeiscontent/storybook-addon-next-router#52]
I got "Cannot read properties of undefined (reading 'name')" using WithNextRouter in story.
```
export default {
  component: Navbar,
  title: "Components/Navbar",
  decorators: [
    withNextRouter,
    (story) => (
      <div
        className="bg-white w-full relative overflow-hidden"
        style={{ height: "4000px" }}
      >
        {story()}
      </div>
    ),
  ],
};
```
Do I even need it to be in export? If I remove withNextRouter then everything works. However, component uses Link from "next/link" and to mock router I believe storybook needs this decorator.

Using "storybook-addon-next-router": "3.1.1" with "next": "10.1.3"

**Comment by pvg8v6g** [comment]
Getting the exact same error with these two packages.

**Comment by crhistianramirez** [comment]
I am seeing the same issue with the following versions:

"storybook-addon-next-router": "3.1.1"
"next": "12.1.0",

**Comment by xmxrkus** [comment]
Same here!

**Comment by lifeiscontent** [comment]
if someone wants to link to a reproduction, I can take a look.

**Comment by lifeiscontent** [comment]
closing due to inactivitiy
