### ISSUE TITLE
Configuring path cannot define router.pathname

### ISSUE THREAD

**Issue by f-katkit** [lifeiscontent/storybook-addon-next-router#61]
I have found that when configuring a router, the "path" definition alone does not change the "router.pathname" in the history book page.

```
versions
next: 12.1.6
storybook-addon-next-router: 4.0.0
```

```
const Template = (args) => <components {. .args} />

export const Comp = Template.bind({})
Comp.parameters = {
  nextRouter: {
    path: "/comps/[pid]",
    asPath: "/comps/3",
    query: {
      id: "3",
    },
  },
```

By setting "pathname" I have defined the "router.pathname" configuration.

↓

```
const Template = (args) => <components {. .args} />

export const Comp = Template.bind({})
Comp.parameters = {
  nextRouter: {
    pathname: "/comps/[pid]",
    asPath: "/comps/3",
    query: {
      id: "3",
    },
  },
```

**Comment by lifeiscontent** [comment]
@f-katkit yep, that's how the internal implementation of the Next.js router works please note that the underlining mock for storybook-addon-next-router is fairly simple as seen here: https://github.com/lifeiscontent/storybook-addon-next-router/blob/master/src/decorators.tsx#L17-L55

**Comment by smaspe** [comment]
This other issue: https://github.com/lifeiscontent/storybook-addon-next-router/issues/46 suggests that is used to work, though?

**Comment by lifeiscontent** [comment]
@smaspe feel free to open a PR, I'm pretty busy right now and won't be able to look into it myself. Also, the storybook team has taken the work from myself and another engineer and integrated it into storybook directly in version 7. You might want to check that out instead as it will make this repo obsolete.
