### ISSUE TITLE
Is it possible to dynamically update the query inside the component?

### ISSUE THREAD

**Issue by markky21** [lifeiscontent/storybook-addon-next-router#62]
I searched the issue and checked the source code and I can't find any information if it is possible to dynamically update the query state of router.

For example, I have a component in which, when I click a button, I perform a push method and update the nextjs router query state `router.push('/?counter=10', undefined, { shallow: true })`. Depending of router query state component display different.

What i want to get?
I wish I could display such a component in my Storybook and notice a change in its state when dispatch push method.

**Comment by lifeiscontent** [comment]
@markky21 please read the docs. You can do anything you want, here's how you can override the push method:

https://github.com/lifeiscontent/storybook-addon-next-router#custom-defaults
