### ISSUE TITLE
Not available in Next13

### ISSUE THREAD

**Issue by mi-upto** [lifeiscontent/storybook-addon-next-router#66]
Are there any plans to support Next13?

**Comment by boreyko1** [comment]
Alternatively, you can add this [override](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) to your `package.json` file
```
  "overrides": {
    "storybook-addon-next-router": {
      "next": "$next"
    }
  }
```

**Comment by bonesoul** [comment]
also looking for next-13 upgrade.
