### ISSUE TITLE
Update to preset

### ISSUE THREAD

**Issue by lifeiscontent** [lifeiscontent/storybook-addon-next-router#7]
I recently upgraded another Storybook Addon to use the Storybook Preset format.

If I updated this Addon to do the same it would eliminate the need for a decorator and you would only have to specify params in your stories.

Here are a couple of ideas I've had about how this could work.

### additions to your main.js

```js
module.exports = {
  ...config,
  addons: [
    ...your addons
    "storybook-addon-next-router",
  ],
};
```

### additions to your preview.js

Simple but potentially will break in the future.

```js
// nothing, you're done.
```

More complicated but will not break in the future.

```js
// If this path changed in Next 11, you'd just update it.
import { RouterContext } from 'next/dist/next-server/lib/router-context';

export const parameters = {
  nextRouter: {
    RouterContext,
  },
};
```

**Comment by lifeiscontent** [comment]
I've been thinking about updating to a new major version for these changes, what do you think?

CC: @bcomnes @tricoder42 @niiccolas

**Comment by bcomnes** [comment]
Yeah whatever makes it more maintainable in the long run. All I need is Link not to break in storybook

**Comment by niicfyi** [comment]
Much cleaner! +1 for a v3
