### ISSUE TITLE
Changing params dynamically 

### ISSUE THREAD

**Issue by IrvingArmenta** [lifeiscontent/storybook-addon-next-router#8]
I'm quite new to storybook, so I'm not sure if this is possible to update the params the `withNextRouter()` decorator. 

I'm using the nextjs router in my components to manage language with the `locale`, I can set the `locale` in this decorator, which works fine, however, I want to be able to update/change this value to another one dynamically using the actual `router.push(path, path, { locale: 'zh' })` for example.

I can see the change in the `Actions` addon, however this does not change anything in the actual decorator.

is there a way to do that?

**Comment by lifeiscontent** [comment]
You can do whatever you want, if you want it done globally you can update it in the decorator, or on a per story basis.

```js
example.story = {
  parameters: {
    nextRouter: {
      path: '/profile/[id]',
      asPath: '/profile/lifeiscontent',
      push() { // what ever you want here }
      query: {
        id: 'lifeiscontent',
      },
    },
  },
};
```

**Comment by lifeiscontent** [comment]
I think that code might be using an old syntax, I can't remember if parameters is a top level key in newer versions of storybook. But you should be good with that info.

**Comment by lifeiscontent** [comment]
@IrvingArmenta
